version: '3.8'

services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: lotto_stat_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lotto_statistics
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d:Z  # <--- MODIFICA QUESTA RIGA
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lotto_stat_backend
    working_dir: /app
    volumes:
      - ./backend:/app:Z
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data: